spring:
  application:
    name: ProjetoLPG1Teste
  datasource:
    url: jdbc:mysql://localhost:3306/rifaTeste
    username: test
    password: IFSP@test
    jdbcDriver: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}